### ISSUE TITLE
Issue on page /intro.html

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy-docs#5]
The "Example notebooks" box does not have a link attached to it like to other ones do.

**Comment by Swanson-Hysell** [comment]
Nice catch. The issues is that example notebooks are now split into: 
<img width="226" alt="Screenshot 2023-12-08 at 11 51 03 AM" src="https://github.com/PmagPy/PmagPy-docs/assets/4332322/a4d2acf4-528e-448b-9442-ab8e98dfeedd">
I will update the link to point to the template ones.
